name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Lint
        run: pnpm lint

      - name: Build All Apps
        run: pnpm build

      - name: Start Backend
        run: pnpm --filter express dev &
      
      - name: Start Frontend
        run: pnpm --filter react dev &

      - name: Wait for frontend
        run: npx wait-on http://localhost:5173

      - name: Wait for backend
        run: npx wait-on http://localhost:5000

      - name: Run Playwright Tests
        run: pnpm test:e2e